INSERT INTO EMPLOYEES (EID, FIRST_NAME, LAST_NAME, PHONE, EMAIL, ESID, EMSID) VALUES (1, 'STEVE', 'MICHAELS', 6985869742, 'SMICHAELS@GMAIL.COM', 1, 1);
/
INSERT INTO EMPLOYEES (EID, FIRST_NAME, LAST_NAME, PHONE, EMAIL, ESID, EMSID) VALUES (2, 'PETER', 'ANDREWS', 6983525567, 'PANDREWS@GMAIL.COM', 2, 2);
/
INSERT INTO EMPLOYEES (EID, FIRST_NAME, LAST_NAME, PHONE, EMAIL, ESID, EMSID) VALUES (3, 'MICHAEL', 'STEVENS', 6989751234, 'MSTEVENS@GMAIL.COM', 3, 3);
/
INSERT INTO EMPLOYEES (EID, FIRST_NAME, LAST_NAME, PHONE, EMAIL, ESID, EMSID) VALUES (4, 'JOHN', 'DOE', 6989245376, 'JDOE@GMAIL.COM', 4, 4);
/
INSERT INTO EMPLOYEES (EID, FIRST_NAME, LAST_NAME, PHONE, EMAIL, ESID, EMSID) VALUES (5, 'MARK', 'HANDELL', 6977946132, 'MHANDELL@GMAIL.COM', 5, 5);
/
INSERT INTO EMPLOYEES (EID, FIRST_NAME, LAST_NAME, PHONE, EMAIL, ESID, EMSID) VALUES (6, 'ANDREW', 'SMITH', 6978524931, 'ASMITH@GMAIL.COM', 6, 6);
/
INSERT INTO EMPLOYEES (EID, FIRST_NAME, LAST_NAME, PHONE, EMAIL, ESID, EMSID) VALUES (7, 'MARY', 'PETERSON', 6977391726, 'MPETERSON@GMAIL.COM', 7, 7);
/
INSERT INTO EMPLOYEES (EID, FIRST_NAME, LAST_NAME, PHONE, EMAIL, ESID, EMSID) VALUES (8, 'ANNA', 'PETERS', 6979617452, 'APETERS@GMAIL.COM', 8, 8);
/
COMMIT;