INSERT INTO PROJECTS (PID, NAME, DESCRIPTION, COMMUNICATION_DATE, REASONING, PCID, PSID, CΟID, CID) VALUES (1, 'CLOUD WEB BROWSER', 'WEB BROWSER CREATION', TO_DATE ('13/MAY/2020'), 'EASY AND LIGHTWEIGHT TO MAINTAIN', 1, 2, 1, 2);
/
INSERT INTO PROJECTS (PID, NAME, DESCRIPTION, COMMUNICATION_DATE, REASONING, PCID, PSID, CΟID, CID) VALUES (2, 'POWERFUL TEXT EDITOR', 'WORD PROCESSOR CREATION', TO_DATE ('29/JAN/2020'), 'EASY AND LIGHTWEIGHT TO MAINTAIN', 1, 4, 2, 3);
/
INSERT INTO PROJECTS (PID, NAME, DESCRIPTION, COMMUNICATION_DATE, REASONING, PCID, PSID, CΟID, CID) VALUES (3, 'MORPHEUS GAME ENGINE', 'GAME ENGINE CREATION', TO_DATE ('7/FEB/2020'), 'WILL ASSIST IN FUTURE PROJECTS', 3, 3, 3, 1);
/
INSERT INTO PROJECTS (PID, NAME, DESCRIPTION, COMMUNICATION_DATE, REASONING, PCID, PSID, CΟID, CID) VALUES (4, 'TEMPLE OS', 'OPERATING SYSTEM CREATION', TO_DATE ('10/MAR/2020'), 'PROJECT WAS TOO COMPLEX', 2, 1, 4, 4);
/
INSERT INTO PROJECTS (PID, NAME, DESCRIPTION, COMMUNICATION_DATE, REASONING, PCID, PSID, CΟID, CID) VALUES (5, 'ANDROID MONITOR', 'ANDROID TASK MONITORING', TO_DATE ('8/APR/2020'), 'ALLOWS IMPROVEMENT OF EXISTING TECHNOLOGIES', 1, 2, 3, 1);
/
INSERT INTO PROJECTS (PID, NAME, DESCRIPTION, COMMUNICATION_DATE, REASONING, PCID, PSID, CΟID, CID) VALUES (6, 'ATM SCANNER', 'FINGERPRINT BASED ATM SYSTEM', TO_DATE ('3/FEB/2020'), 'INNOVATIVE AND COST EFFECTIVE', 1, 2, 1, 2);
/
COMMIT;