INSERT INTO PROJECT_STAGES (STID, DESCRIPTION, DEADLINE, STARTING_DATE, ENDING_DATE, APID) VALUES (1, 'REQUIREMENT GATHERING AND ANALYSIS', TO_DATE ('29/MAY/2020'), TO_DATE ('11/MAY/2020'), TO_DATE ('29/MAY/2020'), 1);
/
INSERT INTO PROJECT_STAGES (STID, DESCRIPTION, DEADLINE, STARTING_DATE, ENDING_DATE, APID) VALUES (2, 'DESIGN', TO_DATE ('19/JUN/2020'), TO_DATE ('1/JUN/2020'), TO_DATE ('19/JUN/2020'), 1);
/
INSERT INTO PROJECT_STAGES (STID, DESCRIPTION, DEADLINE, STARTING_DATE, ENDING_DATE, APID) VALUES (3, 'IMPLEMENTATION OR CODING', TO_DATE ('10/JUL/2020'), TO_DATE ('22/JUN/2020'), TO_DATE ('10/JUL/2020'), 1);
/
INSERT INTO PROJECT_STAGES (STID, DESCRIPTION, DEADLINE, STARTING_DATE, ENDING_DATE, APID) VALUES (4, 'TESTING', TO_DATE ('14/AUG/2020'), TO_DATE ('13/JUL/2020'), TO_DATE ('14/AUG/2020'), 1);
/
INSERT INTO PROJECT_STAGES (STID, DESCRIPTION, DEADLINE, STARTING_DATE, ENDING_DATE, APID) VALUES (5, 'DEPLOYMENT', TO_DATE ('28/AUG/2020'), TO_DATE ('17/AUG/2020'), TO_DATE ('28/AUG/2020'), 1);
/
INSERT INTO PROJECT_STAGES (STID, DESCRIPTION, DEADLINE, STARTING_DATE, ENDING_DATE, APID) VALUES (6, 'MAINTENANCE', TO_DATE ('4/SEP/2020'), TO_DATE ('31/AUG/2020'), TO_DATE ('4/SEP/2020'), 1);
/
INSERT INTO PROJECT_STAGES (STID, DESCRIPTION, DEADLINE, STARTING_DATE, ENDING_DATE, APID) VALUES (7, 'QUALIFICATIONS', TO_DATE ('15/MAY/2020'), TO_DATE ('13/APR/2020'), TO_DATE ('15/MAY/2020'), 2);
/
INSERT INTO PROJECT_STAGES (STID, DESCRIPTION, DEADLINE, STARTING_DATE, ENDING_DATE, APID) VALUES (8, 'DESIGN', TO_DATE ('12/JUN/2020'), TO_DATE ('18/MAY/2020'), TO_DATE ('12/JUN/2020'), 2);
/
INSERT INTO PROJECT_STAGES (STID, DESCRIPTION, DEADLINE, STARTING_DATE, ENDING_DATE, APID) VALUES (9, 'IMPLEMENTATION', TO_DATE ('7/JUL/2020'), TO_DATE ('15/JUN/2020'), TO_DATE ('29/JUN/2020'), 2);
/
INSERT INTO PROJECT_STAGES (STID, DESCRIPTION, DEADLINE, STARTING_DATE, ENDING_DATE, APID) VALUES (10, 'PROJECT SPECIFICATIONS', TO_DATE ('22/MAY/2020'), TO_DATE ('10/FEB/2020'), TO_DATE ('22/MAY/2020'), 3);
/
INSERT INTO PROJECT_STAGES (STID, DESCRIPTION, DEADLINE, STARTING_DATE, ENDING_DATE, APID) VALUES (11, 'DEVELOPMENT', TO_DATE ('17/JUL/2020'), TO_DATE ('25/MAY/2020'), TO_DATE ('17/JUL/2020'), 3);
/
INSERT INTO PROJECT_STAGES (STID, DESCRIPTION, DEADLINE, STARTING_DATE, ENDING_DATE, APID) VALUES (12, 'DEPLOYMENT', TO_DATE ('5/AUG/2020'), TO_DATE ('20/JUL/2020'), TO_DATE ('3/AUG/2020'), 3);
/
COMMIT;