INSERT INTO TOPICS (TID, DESCRIPTION, SPID) VALUES (1, 'IMPROVEMENT OF SYSTEM DESIGN', 1);
/
INSERT INTO TOPICS (TID, DESCRIPTION, SPID) VALUES (2, 'SOFTWARE DESIGN DIFFICULTIES', 4);
/
INSERT INTO TOPICS (TID, DESCRIPTION, SPID) VALUES (3, 'PRODUCT PHILOSOPHY', 18);
/
INSERT INTO TOPICS (TID, DESCRIPTION, SPID) VALUES (4, 'WORKFLOW', 21);
/
COMMIT;