INSERT INTO DOCUMENTS (DID, DESCRIPTION, TID) VALUES (1, 'DESIGN DOCUMENT', 1);
/
INSERT INTO DOCUMENTS (DID, DESCRIPTION, TID) VALUES (2, 'SYSTEM REQUIREMENTS', 2);
/
INSERT INTO DOCUMENTS (DID, DESCRIPTION, TID) VALUES (3, 'MEETING RECORDS', 3);
/
INSERT INTO DOCUMENTS (DID, DESCRIPTION, TID) VALUES (4, 'PRODUCT BACKLOG', 4);
/
COMMIT;