INSERT INTO PROJECT_STATUS (PSID, DESCRIPTION) VALUES (1, 'REJECTED');
/
INSERT INTO PROJECT_STATUS (PSID, DESCRIPTION) VALUES (2, 'ACCEPTED');
/
INSERT INTO PROJECT_STATUS (PSID, DESCRIPTION) VALUES (3, 'IN PROGRESS');
/
INSERT INTO PROJECT_STATUS (PSID, DESCRIPTION) VALUES (4, 'COMPLETED');
/
INSERT INTO PROJECT_STATUS (PSID, DESCRIPTION) VALUES (5, 'CANCELED');
/
COMMIT;