INSERT INTO COMPANY_CATEGORY (CCID, DESCRIPTION) VALUES (1, 'ROYAL CHARTERED COMPANY');
/
INSERT INTO COMPANY_CATEGORY (CCID, DESCRIPTION) VALUES (2, 'STATUTORY COMPANY');
/
INSERT INTO COMPANY_CATEGORY (CCID, DESCRIPTION) VALUES (3, 'REGISTERED OR INCORPORATED COMPANY');
/
INSERT INTO COMPANY_CATEGORY (CCID, DESCRIPTION) VALUES (4, 'COMPANY LIMITED BY SHARES');
/
INSERT INTO COMPANY_CATEGORY (CCID, DESCRIPTION) VALUES (5, 'COMPANY LIMITED BY GUARANTEE');
/
INSERT INTO COMPANY_CATEGORY (CCID, DESCRIPTION) VALUES (6, 'UNLIMITED COMPANY');
/
INSERT INTO COMPANY_CATEGORY (CCID, DESCRIPTION) VALUES (7, 'PUBLIC COMPANY');
/
INSERT INTO COMPANY_CATEGORY (CCID, DESCRIPTION) VALUES (8, 'PRIVATE COMPANY');
/
INSERT INTO COMPANY_CATEGORY (CCID, DESCRIPTION) VALUES (9, 'ONE PERSON COMPANY');
/
COMMIT;