INSERT INTO CUSTOMER_CATEGORY (CUCID, DESCRIPTION) VALUES (1, 'GENERAL MANAGER');
/
INSERT INTO CUSTOMER_CATEGORY (CUCID, DESCRIPTION) VALUES (2, 'ACCOUNTANT');
/
INSERT INTO CUSTOMER_CATEGORY (CUCID, DESCRIPTION) VALUES (3, 'MARKETING EXPERT');
/
INSERT INTO CUSTOMER_CATEGORY (CUCID, DESCRIPTION) VALUES (4, 'ADMINISTRATIVE ASSISTANT');
/
INSERT INTO CUSTOMER_CATEGORY (CUCID, DESCRIPTION) VALUES (5, 'IT TECHNICIAN');
/
INSERT INTO CUSTOMER_CATEGORY (CUCID, DESCRIPTION) VALUES (6, 'HUMAN RESOURCE MANAGER');
/
COMMIT;
