INSERT INTO SUBPROJECT_STAGES (SPSID, DESCRIPTION) VALUES (1, 'WAITING');
/
INSERT INTO SUBPROJECT_STAGES (SPSID, DESCRIPTION) VALUES (2, 'IN PROGRESS');
/
INSERT INTO SUBPROJECT_STAGES (SPSID, DESCRIPTION) VALUES (3, 'COMPLETED');
/
INSERT INTO SUBPROJECT_STAGES (SPSID, DESCRIPTION) VALUES (4, 'CANCELLED');
/
INSERT INTO SUBPROJECT_STAGES (SPSID, DESCRIPTION) VALUES (5, 'ON HOLD');
/
COMMIT;