INSERT INTO EMPLOYEE_SPECIALIZATION (ESID, SPECIALIZATION) VALUES (1, 'PROJECT SPONSOR');
/
INSERT INTO EMPLOYEE_SPECIALIZATION (ESID, SPECIALIZATION) VALUES (2, 'SUBJECT MATTER EXPERT');
/
INSERT INTO EMPLOYEE_SPECIALIZATION (ESID, SPECIALIZATION) VALUES (3, 'PRODUCT OWNER');
/
INSERT INTO EMPLOYEE_SPECIALIZATION (ESID, SPECIALIZATION) VALUES (4, 'PROJECT MANAGER');
/
INSERT INTO EMPLOYEE_SPECIALIZATION (ESID, SPECIALIZATION) VALUES (5, 'TECHNICAL LEAD');
/
INSERT INTO EMPLOYEE_SPECIALIZATION (ESID, SPECIALIZATION) VALUES (6, 'SOFTWARE DEVELOPER');
/
INSERT INTO EMPLOYEE_SPECIALIZATION (ESID, SPECIALIZATION) VALUES (7, 'SOFTWARE TESTER');
/
INSERT INTO EMPLOYEE_SPECIALIZATION (ESID, SPECIALIZATION) VALUES (8, 'USER ACCEPTANCE TESTER');
/
COMMIT;