INSERT INTO EMPLOYEE_SALARIES (EMSID, START_OF_CONTRACT, CONTRACT_EXPIRY, SALARY) VALUES (1, TO_DATE ('6/JAN/2020'), TO_DATE ('6/JAN/2021'), 920);
/
INSERT INTO EMPLOYEE_SALARIES (EMSID, START_OF_CONTRACT, CONTRACT_EXPIRY, SALARY) VALUES (2, TO_DATE ('6/JAN/2020'), TO_DATE ('6/JAN/2021'), 800);
/
INSERT INTO EMPLOYEE_SALARIES (EMSID, START_OF_CONTRACT, CONTRACT_EXPIRY, SALARY) VALUES (3, TO_DATE ('6/JAN/2020'), TO_DATE ('6/JAN/2021'), 880);
/
INSERT INTO EMPLOYEE_SALARIES (EMSID, START_OF_CONTRACT, CONTRACT_EXPIRY, SALARY) VALUES (4, TO_DATE ('6/JAN/2020'), TO_DATE ('6/JAN/2021'), 1000);
/
INSERT INTO EMPLOYEE_SALARIES (EMSID, START_OF_CONTRACT, CONTRACT_EXPIRY, SALARY) VALUES (5, TO_DATE ('6/JAN/2020'), TO_DATE ('6/JAN/2021'), 920);
/
INSERT INTO EMPLOYEE_SALARIES (EMSID, START_OF_CONTRACT, CONTRACT_EXPIRY, SALARY) VALUES (6, TO_DATE ('6/JAN/2020'), TO_DATE ('6/JAN/2021'), 880);
/
INSERT INTO EMPLOYEE_SALARIES (EMSID, START_OF_CONTRACT, CONTRACT_EXPIRY, SALARY) VALUES (7, TO_DATE ('6/JAN/2020'), TO_DATE ('6/JAN/2021'), 920);
/
INSERT INTO EMPLOYEE_SALARIES (EMSID, START_OF_CONTRACT, CONTRACT_EXPIRY, SALARY) VALUES (8, TO_DATE ('6/JAN/2020'), TO_DATE ('6/JAN/2021'), 840);
/
COMMIT;