INSERT INTO COMPANIES (COID, NAME, PHONE, EMAIL, CCID) VALUES (1, 'DATANT', 2108022374, 'DATANTINFO@GMAIL.COM', 2)
/
INSERT INTO COMPANIES (COID, NAME, PHONE, EMAIL, CCID) VALUES (2, 'JOTIVE', 2109438123, 'JOTIVESOLUTIONS@GMAIL.COM', 8)
/
INSERT INTO COMPANIES (COID, NAME, PHONE, EMAIL, CCID) VALUES (3, 'ARTICS', 2107516975, 'ARTICSUNLIMITED@GMAIL.COM', 6)
/
INSERT INTO COMPANIES (COID, NAME, PHONE, EMAIL, CCID) VALUES (4, 'GRANCE', 2107935946, 'GRANCECONTACT@GMAIL.COM', 1)
/
COMMIT;