INSERT INTO CUSTOMERS (CID, FIRST_NAME, LAST_NAME, PHONE, EMAIL, CUCID) VALUES (1, 'PETER', 'ANDERSON', 6983521873, 'PETERANDERSON@GMAIL.COM', 1);
/
INSERT INTO CUSTOMERS (CID, FIRST_NAME, LAST_NAME, PHONE, EMAIL, CUCID) VALUES (2, 'CATHERINE', 'MATHEWS', 6975854397, 'CATHERINEMATHEWS@GMAIL.COM', 6);
/
INSERT INTO CUSTOMERS (CID, FIRST_NAME, LAST_NAME, PHONE, EMAIL, CUCID) VALUES (3, 'ROBERT', 'BLAKE', 6983351352, 'ROBERTBLAKE@GMAIL.COM', 1);
/
INSERT INTO CUSTOMERS (CID, FIRST_NAME, LAST_NAME, PHONE, EMAIL, CUCID) VALUES (4, 'ANNA', 'ROBERTS', 6978761285, 'ANNAROBERTS@GMAIL.COM', 6);
/
COMMIT;