SELECT P.NAME AS "PROJECT NAME", E.FIRST_NAME||' '||E.LAST_NAME AS "EMPLOYEE NAME", SUM (ROUND(ASN.ESTIMATE * ((SP.ENDING_DATE - SP.STARTING_DATE)+1))) AS "ESTIMATED HOURS", SUM (ROUND(ASN.HOURS * ((SP.ENDING_DATE - SP.STARTING_DATE)+1))) AS "PROJECT HOURS"
FROM SUBPROJECTS SP, EMPLOYEES E, ASSIGNMENTS ASN, ASSIGNED_PROJECTS AP, PROJECTS P, PROJECT_STAGES PS
WHERE ASN.SPID = SP.SPID AND ASN.EID = E.EID AND SP.STID = PS.STID AND PS.APID = AP.APID AND P.PID = AP.PID 
GROUP BY P.NAME, E.FIRST_NAME, E.LAST_NAME
