SELECT COUNT(*) AS "NUMBER OF PROJECTS", PROJECT_STATUS.DESCRIPTION AS "PROJECT STATE"
FROM PROJECTS
INNER JOIN PROJECT_STATUS ON PROJECTS.PSID = PROJECT_STATUS.PSID
GROUP BY PROJECT_STATUS.DESCRIPTION
