SELECT P.NAME AS "PROJECT NAME", PS.DESCRIPTION AS "PROJECT PHASE", SP.NAME AS "TASK NAME",
SP.STARTING_DATE AS "TASK STARTING DATE"
FROM ASSIGNED_PROJECTS AP, PROJECTS P, PROJECT_STAGES PS, SUBPROJECTS SP
WHERE AP.PID = P.PID AND PS.APID = AP.APID AND SP.STID = PS.STID
ORDER BY SP.STARTING_DATE ASC
