SELECT P.NAME, AP.BUDGET, E.FIRST_NAME||' '||E.LAST_NAME AS "EMPLOYEE NAME", SUM(ROUND(ASN.ESTIMATE * ((SP.ENDING_DATE-SP.STARTING_DATE)+1)) * ((EMS.SALARY/20)/8)) AS "PROJECT COST PER EMPLOYEE", ROUND(AVG(ASN.PERFORMANCE)) AS PERFORMANCE, ROUND(SUM((ROUND(ASN.HOURS * (SP.ENDING_DATE - SP.STARTING_DATE+1))) * (((EMS.SALARY/20)/8) * (ASN.PERFORMANCE/100)))) AS "EMPLOYEE PAY"
FROM SUBPROJECTS SP, EMPLOYEES E, ASSIGNMENTS ASN, ASSIGNED_PROJECTS AP, PROJECTS P, PROJECT_STAGES PS, EMPLOYEE_SALARIES EMS
WHERE ASN.SPID = SP.SPID AND ASN.EID = E.EID AND E.EMSID = EMS.EMSID AND SP.STID = PS.STID AND PS.APID = AP.APID AND P.PID = AP.PID
GROUP BY P.NAME, AP.BUDGET, E.FIRST_NAME, E.LAST_NAME
