SELECT PR.NAME AS "PROJECT NAME", PR.DESCRIPTION AS "PROJECT DESCRIPTION", CO.NAME AS "COMPANY NAME", CO.PHONE AS "COMPANY PHONE", CU.FIRST_NAME||' '||CU.LAST_NAME AS "CUSTOMER NAME", CU.PHONE AS "CUSTOMER PHONE", E.FIRST_NAME||' '||E.LAST_NAME AS "PROJECT LEADER", E.PHONE AS "PROJECT LEADER PHONE", AP.STARTING_DATE AS "STARTING DATE", AP.DEADLINE, AP.BUDGET
FROM ASSIGNED_PROJECTS AP, PROJECTS PR, COMPANIES CO, CUSTOMERS CU, EMPLOYEES E
WHERE AP.EID = E.EID AND AP.PID = PR.PID AND PR.COID = CO.COID AND PR.CID = CU.CID
ORDER BY AP.STARTING_DATE ASC
