SELECT P.NAME AS "PROJECT NAME", PS.DESCRIPTION AS "PROJECT STAGE", SP.NAME AS "TASK", E.FIRST_NAME||' '||E.LAST_NAME AS "EMPLOYEE NAME", ROUND((SP.ENDING_DATE - SP.STARTING_DATE)+1) AS "TASK DURATION" 
FROM SUBPROJECTS SP, EMPLOYEES E, ASSIGNMENTS ASN, ASSIGNED_PROJECTS AP, PROJECTS P, PROJECT_STAGES PS
WHERE ASN.SPID = SP.SPID AND ASN.EID = E.EID AND SP.STID = PS.STID AND PS.APID = AP.APID AND P.PID = AP.PID AND P.PID = 3
ORDER BY ASN.SPID ASC
