CREATE OR REPLACE TRIGGER TRG_PLIMIT2
BEFORE UPDATE OR INSERT ON ASSIGNMENTS
FOR EACH ROW
DECLARE 
REQUESTED_EID INTEGER;
REQUESTED_APID INTEGER;
NUMBER_OF_PROJECTS_ASSIGNED INTEGER;
TIMES_ASSIGNED_ON_APID INTEGER;
BEGIN
REQUESTED_APID :=:new.APID;
REQUESTED_EID := :new.EID;
SELECT COUNT(DISTINCT APID)
INTO NUMBER_OF_PROJECTS_ASSIGNED 
FROM ASSIGNMENTS
WHERE EID=REQUESTED_EID;
SELECT 
COUNT(*)
INTO TIMES_ASSIGNED_ON_APID
FROM ASSIGNMENTS
WHERE APID=REQUESTED_APID AND EID=REQUESTED_EID; 
IF TIMES_ASSIGNED_ON_APID = 0 AND NUMBER_OF_PROJECTS_ASSIGNED > 1 THEN
RAISE_APPLICATION_ERROR (-20000,'Employee cannot be assigned on a new APID - project');
END IF;
END;
